import streamlit as st
import pandas as pd
from datetime import datetime

from modules.scoring_special_assessment import (
    calculate_special_assessment_scorecard,
    calculate_taxpayer_concentration,
    calculate_value_to_lien,
    calculate_mltm_from_cashflow,
)

from modules.auto_data_sources import (
    auto_pull_structured_data,
    auto_data_results_to_dataframe,
)

from modules.document_ai_extraction import (
    DEFAULT_TARGETS,
    read_uploaded_file_to_context,
    run_document_ai_extraction,
)

from modules.reliability_layer import (
    combine_candidate_sources,
    normalize_candidate_dataframe,
    approved_candidates_to_scorecard_inputs,
    missing_data_tracker,
    source_priority_table,
    build_reliability_summary,
)

st.set_page_config(page_title="Municipal Credit Deal Workspace", layout="wide")

st.title("Municipal Credit Deal Workspace")
st.caption(
    "Deal-first workflow: setup → auto context → document evidence → AI candidate queue → reliability review → scorecard."
)


# =============================================================================
# Advanced Status System
# =============================================================================

STATUS_OPTIONS = {
    "Auto Pulled": {"icon": "🟢", "description": "Pulled from structured public API/data source"},
    "AI Extracted": {"icon": "🔵", "description": "Extracted from uploaded document and approved by analyst"},
    "Calculated": {"icon": "🟣", "description": "Generated by internal calculator/workspace"},
    "Manual Input": {"icon": "🟠", "description": "Entered or overridden manually by analyst"},
    "Needs Review": {"icon": "🟡", "description": "Candidate value exists but requires analyst approval"},
    "Missing": {"icon": "🔴", "description": "No reliable value available yet"},
}


REQUIRED_SCORECARD_FIELDS = [
    {
        "category": "Economic Fundamentals",
        "scorecard_field": "Median Household EBI (% of U.S.)",
        "scorecard_key": "median_household_ebi_percent_of_us",
        "required": True,
    },
    {
        "category": "Economic Fundamentals",
        "scorecard_field": "Unemployment Rate Difference vs U.S. (%)",
        "scorecard_key": "unemployment_rate_difference_vs_us",
        "required": True,
    },
    {
        "category": "Economic Fundamentals",
        "scorecard_field": "MSA Participation",
        "scorecard_key": "msa_participation",
        "required": True,
    },
    {
        "category": "Economic Fundamentals",
        "scorecard_field": "Real Estate Market Volatility",
        "scorecard_key": "real_estate_market_volatility",
        "required": True,
    },
    {
        "category": "Economic Fundamentals",
        "scorecard_field": "Population Growth Difference vs U.S. (%)",
        "scorecard_key": "population_growth_difference_vs_us",
        "required": True,
    },
    {
        "category": "District Characteristics",
        "scorecard_field": "Top 10 Taxpayers as % of Total Levy",
        "scorecard_key": "top10_taxpayers_percent_of_total_levy",
        "required": True,
    },
    {
        "category": "District Characteristics",
        "scorecard_field": "Largest Taxpayer as % of Total Levy",
        "scorecard_key": "largest_taxpayer_percent_of_total_levy",
        "required": True,
    },
    {
        "category": "District Characteristics",
        "scorecard_field": "District Size (Parcels)",
        "scorecard_key": "district_size_parcels",
        "required": True,
    },
    {
        "category": "District Characteristics",
        "scorecard_field": "Conveyance to Homeowners",
        "scorecard_key": "conveyance_to_homeowners",
        "required": True,
    },
    {
        "category": "District Characteristics",
        "scorecard_field": "Est. Value-to-Lien",
        "scorecard_key": "est_value_to_lien",
        "required": True,
    },
    {
        "category": "Financial Profile",
        "scorecard_field": "Maximum Loss-to-Maturity (MLTM) %",
        "scorecard_key": "maximum_loss_to_maturity_percent",
        "required": True,
    },
]


# =============================================================================
# Session Defaults
# =============================================================================

defaults = {
    "approved_inputs": {},
    "approved_input_metadata": {},
    "auto_data_results": [],
    "parsed_documents": [],
    "last_document_ai_result": None,
    "last_scorecard_results": None,
    "review_candidates": pd.DataFrame(),
    "candidate_extractions": [],
    "source_evidence": [],
    "deal_setup": {
        "issuer_name": "Mission Viejo CFD No. 92-1",
        "state": "CA",
        "state_fips": "06",
        "geography_type": "county",
        "county_or_place_fips": "059",
        "county_name": "Orange County",
        "location_name": "Los Angeles-Long Beach-Anaheim",
        "bond_type": "Special Assessment Debt",
        "census_year": 2023,
    },
}

for key, value in defaults.items():
    if key not in st.session_state:
        st.session_state[key] = value


# =============================================================================
# Document Classification
# =============================================================================

def classify_uploaded_file(file_name: str) -> str:
    name = file_name.lower()

    if any(term in name for term in ["os", "official", "statement", "appendix", "appx", "offering"]):
        return "OS / Appendix PDF"

    if any(term in name for term in ["debt service", "debt_service", "ds", "amort", "amortization"]):
        return "Debt Service Excel / Schedule"

    if any(term in name for term in ["mltm", "maximum loss", "loss to maturity", "stress"]):
        return "MLTM Table"

    if any(term in name for term in ["vtl", "value to lien", "value-to-lien", "lien"]):
        return "VTL Workbook"

    if any(term in name for term in ["assessor", "parcel", "county", "assessed value", "av"]):
        return "Assessor Export / County Data"

    return "Unclassified Source Document"


def classify_document_from_text(file_name: str, parsed_text: str, tables=None) -> str:
    name_guess = classify_uploaded_file(file_name)
    text = (parsed_text or "").lower()
    front_text = text[:8000]

    official_statement_signals = [
        "official statement",
        "new issue",
        "book entry only",
        "special tax bonds",
        "special tax refunding bonds",
        "community facilities district",
        "limited obligation bonds",
        "bond counsel",
        "underwriter",
        "security for the bonds",
        "the bonds are payable",
    ]

    appendix_signals = [
        "appendix a",
        "appendix b",
        "assessed valuation",
        "value-to-lien",
        "value to lien",
        "top ten taxpayers",
        "top 10 taxpayers",
        "debt service schedule",
        "direct and overlapping debt",
    ]

    annual_report_signals = [
        "annual report",
        "fiscal year ended",
        "continuing disclosure",
        "annual continuing disclosure",
    ]

    mltm_signals = ["maximum loss-to-maturity", "maximum loss to maturity", "mltm", "loss to maturity"]
    vtl_signals = ["value-to-lien", "value to lien", "assessed value", "direct and overlapping debt"]
    debt_service_signals = ["debt service schedule", "annual debt service", "principal", "interest", "maturity date"]
    assessor_signals = ["assessor", "parcel", "apn", "assessed value roll", "secured tax roll"]

    official_score = sum(signal in front_text or signal in text for signal in official_statement_signals)
    appendix_score = sum(signal in text for signal in appendix_signals)
    annual_score = sum(signal in front_text for signal in annual_report_signals)
    mltm_score = sum(signal in text for signal in mltm_signals)
    vtl_score = sum(signal in text for signal in vtl_signals)
    debt_service_score = sum(signal in text for signal in debt_service_signals)
    assessor_score = sum(signal in text for signal in assessor_signals)

    if official_score >= 2:
        return "OS / Appendix PDF"

    if annual_score >= 1 and appendix_score >= 1:
        return "OS / Appendix PDF"

    if mltm_score >= 1:
        return "MLTM Table"

    if vtl_score >= 2:
        return "VTL Workbook"

    if debt_service_score >= 2:
        return "Debt Service Excel / Schedule"

    if assessor_score >= 2:
        return "Assessor Export / County Data"

    return name_guess


def parse_uploaded_documents(uploaded_files):
    parsed_docs = []

    for uploaded_file in uploaded_files:
        parsed_doc = read_uploaded_file_to_context(uploaded_file)

        detected_type = classify_document_from_text(
            file_name=uploaded_file.name,
            parsed_text=parsed_doc.get("text", ""),
            tables=parsed_doc.get("tables", []),
        )

        parsed_doc["detected_document_type"] = detected_type
        parsed_doc["filename_guess_document_type"] = classify_uploaded_file(uploaded_file.name)
        parsed_docs.append(parsed_doc)

    return parsed_docs


# =============================================================================
# Evidence / Reliability Helpers
# =============================================================================

def evidence_guidance_table():
    return pd.DataFrame(
        [
            {
                "Priority": "Required",
                "Document Type": "OS / Appendix PDF",
                "Why It Matters": "Usually contains deal facts, taxpayer tables, assessed value, district description, debt service, and disclosures.",
                "Typical File Types": "PDF",
                "Workflow Treatment": "Upload first; AI extraction can use it as the main evidence source.",
            },
            {
                "Priority": "Recommended",
                "Document Type": "Debt Service Excel / Schedule",
                "Why It Matters": "Useful for MLTM stress testing, amortization review, and cash flow analysis.",
                "Typical File Types": "XLSX, XLS, CSV",
                "Workflow Treatment": "Upload when doing formal financial profile work.",
            },
            {
                "Priority": "Optional",
                "Document Type": "MLTM Table",
                "Why It Matters": "Supports maximum loss-to-maturity assumptions and stress test review.",
                "Typical File Types": "XLSX, XLS, CSV, PDF",
                "Workflow Treatment": "Upload if available; otherwise use the MLTM calculator.",
            },
            {
                "Priority": "Optional",
                "Document Type": "VTL Workbook",
                "Why It Matters": "Supports value-to-lien calculation and debt burden review.",
                "Typical File Types": "XLSX, XLS, CSV",
                "Workflow Treatment": "Upload if available; otherwise use the Value-to-Lien calculator.",
            },
            {
                "Priority": "Advanced",
                "Document Type": "Assessor Export / County Data",
                "Why It Matters": "Useful for deep-dive parcel, assessed value, or ownership analysis.",
                "Typical File Types": "CSV, XLSX, XLS",
                "Workflow Treatment": "Not needed for quick review; useful for advanced issuer/deal analysis.",
            },
        ]
    )


def uploaded_summary_table(parsed_docs):
    return pd.DataFrame(
        [
            {
                "File Name": doc.get("file_name"),
                "Filename Guess": doc.get("filename_guess_document_type"),
                "Detected Document Type": doc.get("detected_document_type"),
                "Parsed Text Length": len(doc.get("text", "")),
                "Tables Detected": len(doc.get("tables", [])),
            }
            for doc in parsed_docs or []
        ]
    )


def build_evidence_checklist(parsed_docs):
    detected_types = set([doc.get("detected_document_type") for doc in parsed_docs or []])

    required_items = [
        ("Required", "OS / Appendix PDF"),
        ("Recommended", "Debt Service Excel / Schedule"),
        ("Optional", "MLTM Table"),
        ("Optional", "VTL Workbook"),
        ("Advanced", "Assessor Export / County Data"),
    ]

    rows = []

    for priority, doc_type in required_items:
        if doc_type in detected_types:
            status = "Available"
        elif priority == "Required":
            status = "Missing — upload if possible"
        elif priority == "Recommended":
            status = "Not uploaded — recommended for formal review"
        else:
            status = "Not uploaded — optional"

        rows.append({"Priority": priority, "Document Type": doc_type, "Status": status})

    return pd.DataFrame(rows)


def safe_value(value):
    if value is None:
        return None

    if isinstance(value, str) and value.strip() in ["", "None", "nan", "NaN"]:
        return None

    try:
        if pd.isna(value):
            return None
    except Exception:
        pass

    return value


def add_approved_input(
    scorecard_key,
    value,
    status,
    source_method,
    source_document=None,
    confidence=None,
    notes=None,
):
    if value is None:
        return

    st.session_state["approved_inputs"][scorecard_key] = value
    st.session_state["approved_input_metadata"][scorecard_key] = {
        "status": status,
        "source_method": source_method,
        "source_document": source_document,
        "confidence": confidence,
        "reviewed_by": "Analyst" if status in ["AI Extracted", "Manual Input"] else None,
        "review_timestamp": datetime.now().isoformat(timespec="seconds"),
        "notes": notes,
    }


def merge_approved_inputs(new_inputs: dict, status="Auto Pulled", source_method="Auto Data Connector"):
    for key, value in (new_inputs or {}).items():
        add_approved_input(
            scorecard_key=key,
            value=value,
            status=status,
            source_method=source_method,
            confidence=1.0 if status == "Auto Pulled" else None,
            notes=f"{status} value.",
        )


def candidate_row_from_auto_result(item):
    target = item.get("target_data") or item.get("Target Data")
    value = (
        item.get("median_household_ebi_percent_of_us")
        or item.get("value")
        or item.get("Extracted / Calculated Value")
    )

    scorecard_key = None
    scorecard_field = target

    if item.get("median_household_ebi_percent_of_us") is not None:
        scorecard_key = "median_household_ebi_percent_of_us"
        scorecard_field = "Median Household EBI (% of U.S.)"

    if not scorecard_key:
        return None

    return {
        "scorecard_field": scorecard_field,
        "scorecard_key": scorecard_key,
        "value": value,
        "status": "Auto Pulled",
        "source_method": item.get("data_source", "Auto Data Connector"),
        "source_document": None,
        "source_url": item.get("source_url"),
        "confidence": 1.0,
        "notes": item.get("notes", ""),
        "source_excerpt": "",
    }


def sync_candidates_from_sources():
    candidate_rows = []

    for item in st.session_state.get("auto_data_results", []) or []:
        row = candidate_row_from_auto_result(item)
        if row:
            candidate_rows.append(row)

    doc_result = st.session_state.get("last_document_ai_result")

    if doc_result and doc_result.get("ok"):
        extracted = doc_result.get("extracted_fields", []) or doc_result.get("candidates", [])

        for item in extracted:
            scorecard_key = item.get("scorecard_key") or item.get("field_key")
            scorecard_field = item.get("scorecard_field") or item.get("field") or scorecard_key
            value = item.get("value") or item.get("extracted_value") or item.get("numeric_value")
            confidence = item.get("confidence", 0.65)
            source_document = item.get("source_document") or item.get("document") or "Uploaded document"
            source_excerpt = item.get("source_excerpt") or item.get("excerpt") or item.get("evidence") or ""

            if scorecard_key:
                candidate_rows.append(
                    {
                        "scorecard_field": scorecard_field,
                        "scorecard_key": scorecard_key,
                        "value": value,
                        "status": "Needs Review",
                        "source_method": "AI Extraction",
                        "source_document": source_document,
                        "source_url": item.get("source_url", ""),
                        "confidence": confidence,
                        "notes": item.get("notes", ""),
                        "source_excerpt": source_excerpt,
                    }
                )

                if source_excerpt:
                    st.session_state["source_evidence"].append(
                        {
                            "field": scorecard_field,
                            "scorecard_key": scorecard_key,
                            "source_document": source_document,
                            "page": item.get("page", None),
                            "snippet": source_excerpt,
                            "confidence": confidence,
                        }
                    )

    st.session_state["candidate_extractions"] = candidate_rows
    return candidate_rows


def build_data_reliability_matrix():
    approved_inputs = st.session_state.get("approved_inputs", {}) or {}
    approved_meta = st.session_state.get("approved_input_metadata", {}) or {}
    candidates = st.session_state.get("candidate_extractions", []) or []

    rows = []

    for field in REQUIRED_SCORECARD_FIELDS:
        key = field["scorecard_key"]
        value = safe_value(approved_inputs.get(key))
        meta = approved_meta.get(key, {})

        field_candidates = [c for c in candidates if c.get("scorecard_key") == key]
        best_candidate = field_candidates[0] if field_candidates else None

        if value is not None:
            status = meta.get("status", "Manual Input")
            source_method = meta.get("source_method", "")
            source_document = meta.get("source_document", "")
            confidence = meta.get("confidence", None)
            notes = meta.get("notes", "")
        elif best_candidate:
            status = "Needs Review"
            value = best_candidate.get("value")
            source_method = best_candidate.get("source_method", "Candidate")
            source_document = best_candidate.get("source_document", "")
            confidence = best_candidate.get("confidence", None)
            notes = "Candidate exists but has not been approved."
        else:
            status = "Missing"
            value = None
            source_method = ""
            source_document = ""
            confidence = None
            notes = "No value available yet."

        rows.append(
            {
                "category": field["category"],
                "scorecard_field": field["scorecard_field"],
                "scorecard_key": key,
                "status": status,
                "status_icon": STATUS_OPTIONS.get(status, {}).get("icon", ""),
                "current_value": value,
                "source_method": source_method,
                "source_document": source_document,
                "confidence": confidence,
                "required": field["required"],
                "notes": notes,
            }
        )

    return pd.DataFrame(rows)


def render_data_reliability_cards(matrix_df):
    st.subheader("Data Reliability Matrix")

    for category in matrix_df["category"].unique():
        st.markdown(f"### {category}")
        section = matrix_df[matrix_df["category"] == category]

        cols = st.columns(2)

        for idx, (_, row) in enumerate(section.iterrows()):
            with cols[idx % 2]:
                icon = row["status_icon"]
                status = row["status"]
                value = row["current_value"]
                source_method = row["source_method"] or "None"
                confidence = row["confidence"]

                confidence_text = "N/A" if confidence is None or pd.isna(confidence) else f"{float(confidence) * 100:.0f}%"

                st.markdown(
                    f"""
                    <div style="
                        border:1px solid #e5e7eb;
                        border-radius:16px;
                        padding:16px;
                        margin-bottom:12px;
                        background-color:#ffffff;
                        box-shadow:0 1px 3px rgba(0,0,0,0.04);
                    ">
                        <div style="font-size:16px;font-weight:700;margin-bottom:8px;">
                            {row['scorecard_field']}
                        </div>
                        <div style="font-size:14px;margin-bottom:4px;">
                            {icon} <b>{status}</b>
                        </div>
                        <div style="font-size:14px;margin-bottom:4px;">
                            <b>Value:</b> {value}
                        </div>
                        <div style="font-size:14px;margin-bottom:4px;">
                            <b>Source:</b> {source_method}
                        </div>
                        <div style="font-size:14px;">
                            <b>Confidence:</b> {confidence_text}
                        </div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )


def approve_candidate_to_scorecard(candidate, status="AI Extracted"):
    add_approved_input(
        scorecard_key=candidate.get("scorecard_key"),
        value=candidate.get("value"),
        status=status,
        source_method=candidate.get("source_method", "AI Extraction"),
        source_document=candidate.get("source_document"),
        confidence=candidate.get("confidence"),
        notes=candidate.get("notes"),
    )


def get_default_scorecard_inputs():
    approved = st.session_state.get("approved_inputs", {}) or {}

    return {
        "median_household_ebi_percent_of_us": approved.get("median_household_ebi_percent_of_us", 144.0),
        "unemployment_rate_difference_vs_us": approved.get("unemployment_rate_difference_vs_us", -0.3),
        "msa_participation": approved.get("msa_participation", "Yes; Broad & Diverse"),
        "real_estate_market_volatility": approved.get(
            "real_estate_market_volatility",
            "Low Volatility; Stable Prices; Low Distress",
        ),
        "population_growth_difference_vs_us": approved.get("population_growth_difference_vs_us", 0.5),
        "top10_taxpayers_percent_of_total_levy": approved.get("top10_taxpayers_percent_of_total_levy", 16.1),
        "largest_taxpayer_percent_of_total_levy": approved.get("largest_taxpayer_percent_of_total_levy", 6.1),
        "district_size_parcels": approved.get("district_size_parcels", 5900),
        "conveyance_to_homeowners": approved.get(
            "conveyance_to_homeowners",
            "Fairly Developed with Significant Conveyance (Some Developer Concentration)",
        ),
        "est_value_to_lien": approved.get("est_value_to_lien", 15.5),
        "maximum_loss_to_maturity_percent": approved.get("maximum_loss_to_maturity_percent", 13.9),
        "negative_override_notches": approved.get("negative_override_notches", 0),
        "holistic_adjustment_notches": approved.get("holistic_adjustment_notches", 0),
        "rating_cap": approved.get("rating_cap", "None"),
    }


def render_scorecard_results(results: dict):
    st.success("Scorecard calculated.")

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Economic", results.get("economic_fundamentals_assessment"))
    c2.metric("District", results.get("district_characteristics_assessment"))
    c3.metric("Financial", results.get("financial_profile_assessment"))
    c4.metric("Weighted Avg.", results.get("factor_score_weighted_average"))
    c5.metric("Indicative Rating", results.get("indicative_rating"))

    factor_df = pd.DataFrame(
        [
            [
                "Economic Fundamentals Assessment",
                "15%",
                results.get("economic_fundamentals_assessment"),
                results.get("economic_fundamentals_assessment_category"),
            ],
            [
                "District Characteristics Assessment",
                "35%",
                results.get("district_characteristics_assessment"),
                results.get("district_characteristics_assessment_category"),
            ],
            [
                "Financial Profile Assessment",
                "50%",
                results.get("financial_profile_assessment"),
                results.get("financial_profile_assessment_category"),
            ],
        ],
        columns=["Key Credit Factor", "Weight", "Numeric Assessment", "Category"],
    )
    st.dataframe(factor_df, use_container_width=True)

    with st.expander("Rating Explanation", expanded=True):
        st.markdown(results.get("scorecard_explanation", ""))

    with st.expander("Raw Results JSON"):
        st.json(results)


def run_auto_context_pull(deal_setup, census_api_key=None, fred_api_key=None):
    bundle = auto_pull_structured_data(
        state_fips=deal_setup["state_fips"],
        place_or_county=deal_setup["county_or_place_fips"],
        geography_type=deal_setup["geography_type"],
        county_name=deal_setup["county_name"],
        location_name=deal_setup["location_name"],
        census_year=int(deal_setup["census_year"]),
        census_api_key=census_api_key,
        fred_api_key=fred_api_key,
    )

    st.session_state["auto_data_results"] = bundle.get("results", [])
    merge_approved_inputs(bundle.get("approved_inputs", {}), status="Auto Pulled", source_method="Auto Data Connector")
    sync_candidates_from_sources()


def run_document_extraction_pipeline(deal_setup, selected_targets, api_key, model):
    parsed_docs = st.session_state.get("parsed_documents", [])
    if not parsed_docs:
        return {"ok": False, "error": "No parsed documents. Upload source files first."}

    result = run_document_ai_extraction(
        issuer_name=deal_setup["issuer_name"],
        state=deal_setup["state"],
        county_or_region=deal_setup["county_name"],
        bond_type=deal_setup["bond_type"],
        selected_targets=selected_targets,
        parsed_docs=parsed_docs,
        api_key=api_key,
        model=model,
    )

    st.session_state["last_document_ai_result"] = result
    sync_candidates_from_sources()
    return result


# =============================================================================
# Sidebar
# =============================================================================

st.sidebar.header("Scoreboard")
scoreboard_type = st.sidebar.selectbox(
    "Scoreboard Type",
    [
        "Special Assessment Debt",
        "General Obligation / General Fund",
        "Water / Wastewater",
    ],
)

st.sidebar.markdown("---")
st.sidebar.caption("Prototype analyst-support platform. Not an official S&P model.")

if scoreboard_type != "Special Assessment Debt":
    st.header(scoreboard_type)
    st.info("This scoreboard type is reserved for the next build. The deal workspace shell is ready.")
    st.stop()


# =============================================================================
# Main Status Cards
# =============================================================================

auto_count = len(st.session_state.get("auto_data_results", []) or [])
doc_count = len(st.session_state.get("parsed_documents", []) or [])
candidate_count = len(st.session_state.get("candidate_extractions", []) or [])
approved_count = len(st.session_state.get("approved_inputs", {}) or {})

c1, c2, c3, c4 = st.columns(4)
c1.metric("Auto Context Sources", auto_count)
c2.metric("Parsed Documents", doc_count)
c3.metric("Candidate Queue", candidate_count)
c4.metric("Approved Inputs", approved_count)


tab_deal, tab_review, tab_scorecard, tab_calcs, tab_sources = st.tabs(
    [
        "1 Deal Workspace",
        "2 Reliability Review",
        "3 Scorecard",
        "4 Calculators",
        "5 Sources & Evidence",
    ]
)


# =============================================================================
# Tab 1: Deal Workspace
# =============================================================================

with tab_deal:
    st.header("Deal Workspace")
    st.write(
        "Set up the deal once, then run the full pipeline: structured public data + uploaded evidence + AI candidate extraction."
    )

    st.subheader("A. Deal Setup")

    setup = st.session_state.get("deal_setup", defaults["deal_setup"]).copy()

    col1, col2, col3 = st.columns(3)

    with col1:
        issuer_name = st.text_input("Issuer / District Name", value=setup.get("issuer_name", ""))
        state = st.text_input("State", value=setup.get("state", "CA"))
        bond_type = st.selectbox(
            "Bond Type",
            ["Special Assessment Debt", "CFD / Mello-Roos", "Special Tax Bonds"],
            index=0,
        )

    with col2:
        state_fips = st.text_input("State FIPS", value=setup.get("state_fips", "06"))
        geography_type = st.selectbox(
            "Geography Type",
            ["county", "place"],
            index=0 if setup.get("geography_type", "county") == "county" else 1,
        )
        county_or_place_fips = st.text_input(
            "County / Place FIPS",
            value=setup.get("county_or_place_fips", "059"),
            help="County FIPS is 3 digits. Place FIPS is usually 5 digits.",
        )

    with col3:
        county_name = st.text_input("County Name", value=setup.get("county_name", "Orange County"))
        location_name = st.text_input("Location / MSA Name", value=setup.get("location_name", "Los Angeles-Long Beach-Anaheim"))
        census_year = st.number_input("ACS Year", min_value=2018, max_value=2024, value=int(setup.get("census_year", 2023)), step=1)

    deal_setup = {
        "issuer_name": issuer_name,
        "state": state,
        "state_fips": state_fips,
        "geography_type": geography_type,
        "county_or_place_fips": county_or_place_fips,
        "county_name": county_name,
        "location_name": location_name,
        "bond_type": bond_type,
        "census_year": census_year,
    }
    st.session_state["deal_setup"] = deal_setup

    st.markdown("---")
    st.subheader("B. Minimum Viable Evidence")
    st.dataframe(evidence_guidance_table(), use_container_width=True, hide_index=True)

    uploaded_files = st.file_uploader(
        "Upload source files",
        type=["pdf", "csv", "xlsx", "xls", "txt"],
        accept_multiple_files=True,
    )

    if uploaded_files:
        with st.spinner("Parsing uploaded documents and classifying evidence type..."):
            parsed_docs = parse_uploaded_documents(uploaded_files)

        st.session_state["parsed_documents"] = parsed_docs

        st.subheader("Uploaded Evidence Summary")
        st.dataframe(uploaded_summary_table(parsed_docs), use_container_width=True, hide_index=True)

        st.subheader("Evidence Completeness")
        checklist_df = build_evidence_checklist(parsed_docs)
        st.dataframe(checklist_df, use_container_width=True, hide_index=True)

        detected_types = set([doc.get("detected_document_type") for doc in parsed_docs])
        if "OS / Appendix PDF" not in detected_types:
            st.warning("No OS / Appendix PDF detected. You can still proceed, but AI extraction may have limited context.")
        else:
            st.success("Core evidence detected: OS / Appendix PDF is available.")

    elif st.session_state.get("parsed_documents"):
        parsed_docs = st.session_state.get("parsed_documents")
        st.subheader("Uploaded Evidence Summary")
        st.dataframe(uploaded_summary_table(parsed_docs), use_container_width=True, hide_index=True)
        st.subheader("Evidence Completeness")
        st.dataframe(build_evidence_checklist(parsed_docs), use_container_width=True, hide_index=True)
    else:
        st.info("No parsed documents yet.")

    st.markdown("---")
    st.subheader("C. Run Deal Intelligence Pipeline")

    p1, p2 = st.columns(2)

    with p1:
        try:
            default_census_key = st.secrets.get("CENSUS_API_KEY", "")
        except Exception:
            default_census_key = ""
        try:
            default_fred_key = st.secrets.get("FRED_API_KEY", "")
        except Exception:
            default_fred_key = ""

        census_api_key = st.text_input("Census API Key Override", type="password", value="")
        fred_api_key = st.text_input("FRED API Key Override", type="password", value="")

    with p2:
        try:
            default_openai_key = st.secrets.get("OPENAI_API_KEY", "")
        except Exception:
            default_openai_key = ""

        openai_api_key = st.text_input("OpenAI API Key Override", type="password", value="")
        model = st.selectbox("OpenAI Model", ["gpt-4.1-mini", "gpt-4.1", "gpt-4o-mini"], index=0)

    selected_targets = st.multiselect(
        "Fields to Extract from Uploaded Documents",
        DEFAULT_TARGETS,
        default=DEFAULT_TARGETS,
    )

    run_col1, run_col2, run_col3 = st.columns([1.1, 1.1, 2])

    with run_col1:
        run_auto_only = st.button("Run Auto Context Only")

    with run_col2:
        run_full = st.button("Run Deal Intelligence Pipeline", type="primary")

    with run_col3:
        st.caption("Pipeline = public data context + uploaded document extraction + candidate reliability review.")

    if run_auto_only:
        with st.spinner("Pulling structured public data..."):
            run_auto_context_pull(
                deal_setup,
                census_api_key=census_api_key or default_census_key or None,
                fred_api_key=fred_api_key or default_fred_key or None,
            )
        st.success("Auto context pull completed.")

    if run_full:
        with st.spinner("Step 1/2: Pulling structured public data..."):
            run_auto_context_pull(
                deal_setup,
                census_api_key=census_api_key or default_census_key or None,
                fred_api_key=fred_api_key or default_fred_key or None,
            )

        if st.session_state.get("parsed_documents"):
            with st.spinner("Step 2/2: Running document AI extraction..."):
                result = run_document_extraction_pipeline(
                    deal_setup=deal_setup,
                    selected_targets=selected_targets,
                    api_key=openai_api_key or default_openai_key,
                    model=model,
                )

            if result.get("ok", False):
                st.success("Deal intelligence pipeline completed.")
            else:
                st.warning(result.get("error", "Document extraction did not complete. Auto context was still pulled."))
        else:
            st.warning("Auto context completed. No documents uploaded, so document extraction was skipped.")

    if st.session_state.get("auto_data_results"):
        st.subheader("Auto Context Results")
        st.dataframe(auto_data_results_to_dataframe(st.session_state["auto_data_results"]), use_container_width=True)

    if st.session_state.get("parsed_documents"):
        st.subheader("Parsed Document Preview")
        for doc in st.session_state.get("parsed_documents", []):
            title = f"{doc.get('file_name')} — {doc.get('detected_document_type', 'Unclassified')}"
            with st.expander(title, expanded=False):
                if doc.get("warnings"):
                    for warning in doc.get("warnings"):
                        st.warning(warning)
                st.text_area("Parsed Text Preview", doc.get("text", "")[:5000], height=220)
                for table in doc.get("tables", []):
                    st.write(table.get("table_name"))
                    st.dataframe(pd.DataFrame(table.get("preview", [])), use_container_width=True)


# =============================================================================
# Tab 2: Reliability Review
# =============================================================================

with tab_review:
    st.header("Reliability Review")

    matrix_df = build_data_reliability_matrix()
    render_data_reliability_cards(matrix_df)

    st.markdown("---")
    st.subheader("AI Candidate Extraction Queue")

    candidates = st.session_state.get("candidate_extractions", []) or []

    if not candidates:
        st.info("No AI candidate values yet. Run the Deal Intelligence Pipeline first.")
    else:
        for idx, candidate in enumerate(candidates):
            with st.container(border=True):
                c1, c2, c3, c4 = st.columns([2, 1, 1, 1])

                with c1:
                    st.markdown(f"### {candidate.get('scorecard_field')}")
                    st.write(f"**Scorecard Key:** `{candidate.get('scorecard_key')}`")
                    st.write(f"**Source:** {candidate.get('source_method')} — {candidate.get('source_document')}")

                with c2:
                    st.metric("Candidate Value", candidate.get("value"))

                with c3:
                    confidence = candidate.get("confidence")
                    confidence_display = "N/A" if confidence is None else f"{float(confidence) * 100:.0f}%"
                    st.metric("Confidence", confidence_display)

                with c4:
                    status = candidate.get("status", "Needs Review")
                    icon = STATUS_OPTIONS.get(status, {}).get("icon", "")
                    st.write(f"{icon} **{status}**")

                if candidate.get("source_excerpt"):
                    with st.expander("Evidence Excerpt"):
                        st.write(candidate.get("source_excerpt"))

                a1, a2, a3 = st.columns([1, 1, 3])

                with a1:
                    if st.button("Approve", key=f"approve_candidate_{idx}"):
                        candidate["status"] = "AI Extracted"
                        approve_candidate_to_scorecard(candidate, status="AI Extracted")
                        st.success("Candidate approved to scorecard.")

                with a2:
                    if st.button("Reject", key=f"reject_candidate_{idx}"):
                        candidate["status"] = "Missing"
                        st.warning("Candidate rejected.")

                with a3:
                    override_value = st.text_input(
                        "Analyst Override Value",
                        key=f"override_candidate_{idx}",
                        value="",
                    )
                    if st.button("Approve Override", key=f"approve_override_{idx}"):
                        if override_value.strip():
                            candidate["value"] = override_value.strip()
                            candidate["status"] = "Manual Input"
                            approve_candidate_to_scorecard(candidate, status="Manual Input")
                            st.success("Manual override approved to scorecard.")

    st.markdown("---")
    st.subheader("Reliability Matrix Table")
    st.dataframe(build_data_reliability_matrix(), use_container_width=True)


# =============================================================================
# Tab 3: Scorecard
# =============================================================================

with tab_scorecard:
    st.header("Special Assessment Debt Scorecard")

    defaults_for_scorecard = get_default_scorecard_inputs()
    st.info("Values below may be prefilled from approved Reliability Review inputs. You can still manually override them.")

    with st.expander("A. Economic Fundamentals Assessment", expanded=True):
        col1, col2 = st.columns(2)

        with col1:
            median_household_ebi_percent_of_us = st.number_input(
                "Median Household EBI (% of U.S.)",
                min_value=0.0,
                max_value=500.0,
                value=float(defaults_for_scorecard["median_household_ebi_percent_of_us"]),
                step=1.0,
            )
            unemployment_rate_difference_vs_us = st.number_input(
                "Unemployment Rate Difference vs U.S. (%)",
                value=float(defaults_for_scorecard["unemployment_rate_difference_vs_us"]),
                step=0.1,
            )
            population_growth_difference_vs_us = st.number_input(
                "Population Growth Difference vs U.S. (%)",
                value=float(defaults_for_scorecard["population_growth_difference_vs_us"]),
                step=0.1,
            )

        with col2:
            msa_options = ["Yes; Broad & Diverse", "Yes; Not Broad & Diverse", "No"]
            msa_default = defaults_for_scorecard.get("msa_participation", msa_options[0])
            msa_index = msa_options.index(msa_default) if msa_default in msa_options else 0
            msa_participation = st.selectbox("MSA Participation", msa_options, index=msa_index)

            re_options = [
                "Low Volatility; Stable Prices; Low Distress",
                "Elevated Volatility; Stable Prices; Affordability Worse Than National Figures",
                "Falling Local Home Prices; High Price Volatility; Low Affordability; Rising Distress",
                "Falling Local Home Prices; High Price Volatility; Significantly Worse Affordability; Rising Distress",
            ]
            re_default = defaults_for_scorecard.get("real_estate_market_volatility", re_options[0])
            re_index = re_options.index(re_default) if re_default in re_options else 0
            real_estate_market_volatility = st.selectbox("Real Estate Market Volatility", re_options, index=re_index)

    with st.expander("B. District Characteristics Assessment", expanded=True):
        col3, col4 = st.columns(2)

        with col3:
            top10_taxpayers_percent_of_total_levy = st.number_input(
                "Top 10 Taxpayers as % of Total Levy",
                min_value=0.0,
                max_value=100.0,
                value=float(defaults_for_scorecard["top10_taxpayers_percent_of_total_levy"]),
                step=0.1,
            )
            largest_taxpayer_percent_of_total_levy = st.number_input(
                "Largest Taxpayer as % of Total Levy",
                min_value=0.0,
                max_value=100.0,
                value=float(defaults_for_scorecard["largest_taxpayer_percent_of_total_levy"]),
                step=0.1,
            )
            district_size_parcels = st.number_input(
                "District Size (Parcels)",
                min_value=0,
                value=int(float(defaults_for_scorecard["district_size_parcels"])),
                step=100,
            )

        with col4:
            conveyance_options = [
                "All or Nearly All Conveyed",
                "Most Conveyed",
                "Fairly Developed with Significant Conveyance (Some Developer Concentration)",
                "Developed; Significant Undeveloped Parcels Comprise Minority (Large Developer Concentration)",
                "Undeveloped with Limited Vertical Construction; High Concentration",
            ]
            conv_default = defaults_for_scorecard.get("conveyance_to_homeowners", conveyance_options[2])
            conv_index = conveyance_options.index(conv_default) if conv_default in conveyance_options else 2
            conveyance_to_homeowners = st.selectbox("Conveyance to Homeowners", conveyance_options, index=conv_index)

            est_value_to_lien = st.number_input(
                "Est. Value-to-Lien",
                min_value=0.0,
                value=float(defaults_for_scorecard["est_value_to_lien"]),
                step=0.1,
            )

    with st.expander("C. Financial Profile Assessment", expanded=True):
        maximum_loss_to_maturity_percent = st.number_input(
            "Maximum Loss-to-Maturity (MLTM) %",
            min_value=0.0,
            max_value=100.0,
            value=float(defaults_for_scorecard["maximum_loss_to_maturity_percent"]),
            step=0.1,
        )

    with st.expander("D. Overriding Factors / Caps / Holistic Analysis", expanded=False):
        col5, col6, col7 = st.columns(3)
        with col5:
            negative_override_notches = st.number_input(
                "Negative Overriding Factors (Notches)",
                min_value=0,
                max_value=5,
                value=0,
                step=1,
            )
        with col6:
            holistic_adjustment_notches = st.number_input(
                "Holistic Analysis Adjustment (Notches)",
                min_value=-1,
                max_value=1,
                value=0,
                step=1,
            )
        with col7:
            rating_cap = st.selectbox("Rating Cap", ["None", "bbb", "bb", "b category"])

    scorecard_inputs = {
        "median_household_ebi_percent_of_us": median_household_ebi_percent_of_us,
        "unemployment_rate_difference_vs_us": unemployment_rate_difference_vs_us,
        "msa_participation": msa_participation,
        "real_estate_market_volatility": real_estate_market_volatility,
        "population_growth_difference_vs_us": population_growth_difference_vs_us,
        "top10_taxpayers_percent_of_total_levy": top10_taxpayers_percent_of_total_levy,
        "largest_taxpayer_percent_of_total_levy": largest_taxpayer_percent_of_total_levy,
        "district_size_parcels": district_size_parcels,
        "conveyance_to_homeowners": conveyance_to_homeowners,
        "est_value_to_lien": est_value_to_lien,
        "maximum_loss_to_maturity_percent": maximum_loss_to_maturity_percent,
        "negative_override_notches": negative_override_notches,
        "holistic_adjustment_notches": holistic_adjustment_notches,
        "rating_cap": rating_cap,
    }

    if st.button("Calculate Scorecard", type="primary"):
        results = calculate_special_assessment_scorecard(scorecard_inputs)
        st.session_state["last_scorecard_results"] = results
        render_scorecard_results(results)


# =============================================================================
# Tab 4: Calculators
# =============================================================================

with tab_calcs:
    st.header("Analytical Calculators")

    calc_tab1, calc_tab2, calc_tab3 = st.tabs(["Taxpayer Concentration", "Value-to-Lien", "MLTM Stress Test"])

    with calc_tab1:
        st.subheader("Taxpayer Concentration Builder")
        default_taxpayers = pd.DataFrame(
            {
                "taxpayer_name": [
                    "Lennar Landbank",
                    "Lennar",
                    "Risewell Landbank",
                    "Risewell",
                    "Beazer Landbank",
                    "Beazer",
                    "Dignity Community Care",
                    "Ridge EG West LP",
                    "PF Portfolio 2 LP",
                    "EGBL 15 LLC",
                ],
                "levy_percent": [6.1, 0.0, 4.0, 0.0, 1.5, 0.0, 1.5, 1.4, 0.9, 0.7],
            }
        )

        taxpayer_df = st.data_editor(default_taxpayers, num_rows="dynamic", use_container_width=True)

        if st.button("Calculate Taxpayer Concentration"):
            concentration = calculate_taxpayer_concentration(taxpayer_df)
            add_approved_input(
                "top10_taxpayers_percent_of_total_levy",
                concentration["top10_taxpayers_percent_of_total_levy"],
                status="Calculated",
                source_method="Taxpayer Concentration Builder",
                confidence=1.0,
            )
            add_approved_input(
                "largest_taxpayer_percent_of_total_levy",
                concentration["largest_taxpayer_percent_of_total_levy"],
                status="Calculated",
                source_method="Taxpayer Concentration Builder",
                confidence=1.0,
            )
            c1, c2 = st.columns(2)
            c1.metric("Top 10 Taxpayers %", concentration["top10_taxpayers_percent_of_total_levy"])
            c2.metric("Largest Taxpayer %", concentration["largest_taxpayer_percent_of_total_levy"])
            st.dataframe(concentration["taxpayer_table"], use_container_width=True)

    with calc_tab2:
        st.subheader("Value-to-Lien Calculator")
        col1, col2 = st.columns(2)

        with col1:
            assessed_value = st.number_input("Assessed Value", min_value=0.0, value=3454244692.0, step=1000000.0)
            direct_debt = st.number_input("Direct Debt", min_value=0.0, value=183240000.0, step=1000000.0)

        with col2:
            overlapping_debt = st.number_input("Overlapping Debt", min_value=0.0, value=38445099.0, step=1000000.0)
            include_overlapping_debt = st.checkbox("Include Overlapping Debt", value=True)

        if st.button("Calculate Value-to-Lien"):
            vtl_results = calculate_value_to_lien(assessed_value, direct_debt, overlapping_debt, include_overlapping_debt)
            add_approved_input(
                "est_value_to_lien",
                vtl_results["estimated_value_to_lien"],
                status="Calculated",
                source_method="Value-to-Lien Calculator",
                confidence=1.0,
            )
            c1, c2 = st.columns(2)
            c1.metric("Debt Base", f"{vtl_results['debt_base_for_vtl']:,.0f}")
            c2.metric("Est. Value-to-Lien", vtl_results["estimated_value_to_lien"])
            st.json(vtl_results)

    with calc_tab3:
        st.subheader("Maximum Loss-to-Maturity Stress Test")
        initial_reserve_fund = st.number_input("Initial Reserve Fund", min_value=0.0, value=15439154.0, step=100000.0)

        default_cashflow = pd.DataFrame(
            {
                "year": list(range(2027, 2037)),
                "special_tax_levy": [
                    12191803,
                    12460759,
                    12710019,
                    12959939,
                    13219518,
                    13492483,
                    13758628,
                    14025653,
                    14138513,
                    14239823,
                ],
                "annual_debt_service": [
                    11108912,
                    11327963,
                    11554563,
                    11781763,
                    12017744,
                    12265894,
                    12507844,
                    12750594,
                    12853194,
                    12945294,
                ],
            }
        )

        cashflow_df = st.data_editor(default_cashflow, num_rows="dynamic", use_container_width=True)

        if st.button("Calculate MLTM"):
            mltm_results = calculate_mltm_from_cashflow(cashflow_df, initial_reserve_fund=initial_reserve_fund)
            add_approved_input(
                "maximum_loss_to_maturity_percent",
                mltm_results["maximum_loss_to_maturity_percent"],
                status="Calculated",
                source_method="MLTM Stress Test",
                confidence=1.0,
            )
            c1, c2, c3 = st.columns(3)
            c1.metric("Estimated MLTM %", mltm_results["maximum_loss_to_maturity_percent"])
            c2.metric("Total Revenue", f"{mltm_results['total_revenue']:,.0f}")
            c3.metric("Total Debt Service", f"{mltm_results['total_debt_service']:,.0f}")
            st.dataframe(mltm_results["mltm_cashflow_table"], use_container_width=True)


# =============================================================================
# Tab 5: Sources & Evidence
# =============================================================================

with tab_sources:
    st.header("Sources & Evidence")

    st.subheader("Source Priority Engine")
    st.dataframe(source_priority_table(), use_container_width=True)

    st.subheader("Data Reliability Matrix")
    st.dataframe(build_data_reliability_matrix(), use_container_width=True)

    st.subheader("Approved Scorecard Inputs")
    approved = st.session_state.get("approved_inputs", {}) or {}
    approved_meta = st.session_state.get("approved_input_metadata", {}) or {}

    approved_rows = []
    for key, value in approved.items():
        meta = approved_meta.get(key, {})
        approved_rows.append(
            {
                "scorecard_key": key,
                "value": value,
                "status": meta.get("status"),
                "source_method": meta.get("source_method"),
                "source_document": meta.get("source_document"),
                "confidence": meta.get("confidence"),
                "reviewed_by": meta.get("reviewed_by"),
                "review_timestamp": meta.get("review_timestamp"),
                "notes": meta.get("notes"),
            }
        )
    st.dataframe(pd.DataFrame(approved_rows), use_container_width=True)

    st.subheader("AI Candidate Queue")
    st.dataframe(pd.DataFrame(st.session_state.get("candidate_extractions", [])), use_container_width=True)

    st.subheader("Source Evidence Viewer")
    evidence = st.session_state.get("source_evidence", []) or []
    if not evidence:
        st.info("No source evidence captured yet.")
    else:
        for item in evidence:
            with st.expander(item.get("field", "Evidence")):
                st.write(f"**Document:** {item.get('source_document')}")
                st.write(f"**Page:** {item.get('page')}")
                st.write(f"**Confidence:** {item.get('confidence')}")
                st.code(item.get("snippet", ""))

    st.subheader("Auto Context Results")
    if st.session_state.get("auto_data_results"):
        st.dataframe(auto_data_results_to_dataframe(st.session_state["auto_data_results"]), use_container_width=True)
    else:
        st.info("No auto context results yet.")

    st.subheader("Parsed Document Inventory")
    parsed_docs = st.session_state.get("parsed_documents", [])
    if parsed_docs:
        st.dataframe(uploaded_summary_table(parsed_docs), use_container_width=True, hide_index=True)
        st.dataframe(build_evidence_checklist(parsed_docs), use_container_width=True, hide_index=True)
    else:
        st.info("No documents parsed yet.")

    if st.session_state.get("last_scorecard_results"):
        st.subheader("Latest Scorecard Explanation")
        st.markdown(st.session_state["last_scorecard_results"].get("scorecard_explanation", ""))
